apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: y74rdngae-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/rhtap-qe-java-quarkus:e017d99ad9f6089aac2644e49bbaa0fb78e65957@sha256:b864b9e561757a68b60fed05fbb841fd0e2aa7c0bb851a0892789a689607893d
        name: container-image  
